# Generated by Django 4.2.7 on 2023-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('bright', 'Bright'), ('fun', 'Fun'), ('angry', 'Angry'), ('aggressive', 'Aggressive'), ('sad', 'Sad'), ('bitter', 'Bitter'), ('relaxed', 'Relaxed'), ('lonely', 'Lonely'), ('energetic', 'Energetic'), ('soothing', 'Soothing'), ('peacefull', 'Peacefull'), ('soft', 'Calm')], max_length=20)),
                ('songName', models.TextField(max_length=100)),
                ('artist', models.TextField(max_length=100)),
                ('coverImage', models.URLField()),
                ('audioFile', models.FileField(upload_to='')),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
