# Generated by Django 4.1.6 on 2023-10-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.IntegerField(verbose_name='labels')),
                ('uri', models.CharField(max_length=255, verbose_name='uri')),
            ],
        ),
    ]
